version: "3.3"
services:

  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - nginx_frontend
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "2"
    volumes:
      - ./nginx/:/etc/nginx/

networks:
  nginx_frontend:
    external: true
